### ISSUE TITLE
Separate documentation on how to customize templates

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tomtoolkit.github.io#11]
Most astronomers are unfamiliar with templates as a concept, and will not know how Django finds the template for each view.  Some of this information is covered under the "Plotting Data" topic, but a user may not easily find this unless they happen to be including a plot.  
Also, additional information on how the templates in my TOM override those from the base Toolkit would be very helpful.

**Comment by Fingel** [comment]
This doc was one of the first we ever wrote. Is it not sufficient? https://tomtoolkit.github.io/docs/customize_templates

**Comment by rachel3834** [comment]
That document is good, but doesn't cover quite what I needed in sufficient detail.  The new doc you shared on slack is what I was looking for.

**Comment by Fingel** [comment]
In that case, can we close this bug? I also closed #10 with that latest doc update, I'm not sure if that was what you were looking for.
