### ISSUE TITLE
What are Target 'tags' and how do I use them?

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tomtoolkit.github.io#12]
As a TOM user, I've just tried to add a target to my TOM and the form asks me to assign a series of tags in the form of key-value pairs.  What is the significance of these and how should I use them?  Are they the equivalent of keywords for later searches?

**Comment by Fingel** [comment]
I added some info the the FAQ for this: https://github.com/TOMToolkit/tomtoolkit.github.io/commit/c148016403bcd3703e149e28eded2bd165a5eaa0
